2017pro02/medical-web

- .circleci/config.yml
- README.md
今後の開発に備えて、CircleCIでテストするようにした。
#6
> CircleCIでテストするようにした

- app/controllers/meals_controller.rb
- app/models/comment.rb
- app/models/meal.rb
- app/models/user.rb
- app/views/meals/show.html.erb
- app/views/user_profile/show.html.erb
- config/routes.rb
- db/migrate/20171008055732_create_comments.rb
- db/schema.rb
- spec/factories/comments.rb
- spec/models/comment_spec.rb
> Webから高齢者の食事を確認でき、コメントできるようにした

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/controllers/meals_controller.rb
- app/models/user.rb
- app/views/errors/403.html
- app/views/layouts/application.html.erb
- app/views/meals/index.html.erb
- app/views/meals/show.html.erb
- app/views/pages/dashboard.html.erb
- config/locales/models/comment.ja.yml
- config/locales/models/meal.ja.yml
- config/locales/models/relation.ja.yml
今までは食事一覧の表示にtableを使用していたが、新たにカレンダーを導入して分かりやすく表示するようにした。
また赤の他人の料理が見れないようにして、不正にアクセスしても弾くようにした。
close #16
> カレンダー表示を追加した

- .circleci/config.yml
- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- config/database.yml
- docker-compose.yml
ついに移行。これでHerokuにデプロイできる。
close #18
> DBをsqliteからpostgresに移行

- app/models/user.rb
- config/application.rb
- config/cable.yml
- config/database.yml
- config/environments/heroku.rb
- config/environments/production.rb
- config/secrets.yml
- package.json
- spec/models/user_spec.rb
http://stormy-ocean-60686.herokuapp.com にデプロイした。
close #21
> Herokuにデプロイした

- app/models/comment.rb
- db/migrate/20171008055732_create_comments.rb
- db/schema.rb
ちょっとよろしくないリレーションになっていたので、修正した。
close #34
> CommentのUser周りの外部キー制約に失敗していたのでmigrationを修正した

- app/views/layouts/application.html.erb
> viewportを指定していなかったので指定した

- app/helpers/application_helper.rb
- app/models/user_profile.rb
- app/views/devise/registrations/edit.html.erb
- app/views/users/edit.html.erb
- config/application.rb
今まではバリデーションを設定していなくて、500エラーが発生していたところを修正した。
close #45
> 既存のユーザー名に変更してもきちんとエラーを出すようにした

- Gemfile
- Gemfile.lock
> foremanを追加した

- app/controllers/meals_controller.rb
> 料理追加時の通知を修正した

- README.md
> READMEのセットアップ方法辺りを更新

- app/javascript/comment.vue
> オススメ料理をダミーで表示するようにした

- app/controllers/pages_controller.rb
- app/javascript/meal.vue
- app/views/meals/_meal.json.jbuilder
- app/views/meals/index.html.erb
- app/views/meals/show.html.erb
- app/views/meals/show.json.jbuilder
- app/views/pages/tv.json.jbuilder
- bin/webpack
- bin/webpack-dev-server
- bin/yarn
- config/application.rb
> [WIP] 食事の表示を修正する

- Gemfile
- Gemfile.lock
- app/uploaders/avatar_uploader.rb
- config/environments/heroku.rb
> AWSへのアップロードに成功！

- app/jobs/guess_dish_job.rb
- app/jobs/guess_food_job.rb
- spec/jobs/guess_food_job_spec.rb
> CutouterJob実行時にS3から画像を取得できない問題を解決

- app/assets/stylesheets/meals.scss
- app/controllers/pages_controller.rb
- app/views/meals/index.html.erb
- app/views/simple_calendar/_calendar.html.erb
- app/views/simple_calendar/_month_calendar.html.erb
- app/views/simple_calendar/_week_calendar.html.erb
- config/application.rb
* タイトルを修正
* 上の操作系統の見栄えを良くした
close #82 
close #84
> カレンダーの上の方を修正

- app/assets/stylesheets/meals.scss
- app/assets/stylesheets/pages.scss
- app/views/pages/index.html.erb
見た目はザ・Bootstrapだけど、FlexLayoutとか色々使ってるよ！
close #71
> トップページを作成した

- app/controllers/meals_controller.rb
- app/models/user.rb
> meals#showで他人の食事が表示されるヤバいバグを修正

- app/assets/stylesheets/pages.scss
- app/views/pages/dashboard.html.erb
- app/views/pages/index.html.erb
- config/initializers/time_formats.rb
> ダッシュボードを良い感じにした

- app/views/layouts/application.html.erb
- app/views/pages/index.html.erb
文言は適宜修正する。
close #88 
close #93
> トップ画面にサービス利用開始の導線を設置

- Gemfile
- Gemfile.lock
- spec/controllers/pages_controller_spec.rb
- spec/controllers/users_controller_spec.rb
- spec/factories/comments.rb
- spec/factories/dishes.rb
- spec/factories/meals.rb
- spec/factories/nutritions.rb
- spec/factories/relations.rb
- spec/factories/user_profiles.rb
- spec/factories/users.rb
- spec/models/user_profile_spec.rb
毎回アップグレードしろって警告が五月蝿いので、渋々アップグレード。
close #61
> FactoryGirlをFactoryBotにアップグレード

- .gitignore
- app/javascript/comment.vue
- app/views/pages/tv.html.erb
- config/initializers/assets.rb
- config/initializers/time_formats.rb
- lib/tasks/deploy_sounds.rake
これでユーザーは音でコメントに気付ける。
close #81
> テレビでコメントを受信したら音が鳴るようにした

- app/assets/javascripts/meals.coffee
- app/assets/stylesheets/meals.scss
- app/helpers/meals_helper.rb
- app/views/meals/index.html.erb
- app/views/simple_calendar/_month_calendar.html.erb
- app/views/simple_calendar/_week_calendar.html.erb
こんな感じで。
close #101 
close #103
> カレンダーに週表示を追加した

- app/assets/javascripts/channels/web_notification.coffee
- app/channels/web_notification_channel.rb
- app/controllers/meals_controller.rb
- app/javascript/comment.vue
> 食事が撮影されると、家族や医療従事者にWebNotifyされるようにした

- Gemfile
- Gemfile.lock
- app/controllers/nutritions_controller.rb
- app/javascript/comment.vue
- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- app/views/nutritions/index.html.erb
- spec/views/nutritions/index.html.erb_spec.rb
> ページネーションを導入した

- app/assets/javascripts/pages.coffee
- app/assets/stylesheets/pages.scss
- app/assets/stylesheets/sticky-footer.css
- app/views/layouts/application.html.erb
- app/views/pages/index.html.erb
- config/breadcrumbs.rb
良い感じにした。
close #89 
close #104 
close #112
> フッター付けて、トップページを整えた

- db/fixtures/01_user.rb
男性か女性か設定して、20歳から80歳の間でランダムに設定する。
close #114
> テストユーザーに性別と年齢を設定するようにした

- app/assets/javascripts/pages.coffee
- app/assets/stylesheets/sticky-footer.css
- app/controllers/pages_controller.rb
- app/javascript/comment.vue
- app/views/pages/tv.json.jbuilder
觀自在菩薩。行深般若波羅蜜多時。照見五蘊皆空。度一切苦厄。
舍利子。色不異空。空不異色。色即是空。空即是色。受想行識亦復如是。
舍利子。是諸法空相。不生不滅。不垢不淨不増不減。
是故空中。無色。無受想行識。無眼耳鼻舌身意。無色聲香味觸法。無眼界。乃至無意識界。
無無明。亦無無明盡。乃至無老死。亦無老死盡。無苦集滅道。無智亦無得。
以無所得故。菩提薩埵。依般若波羅蜜多故。心無罣礙。無罣礙故。無有恐怖。遠離顛倒夢想。究竟涅槃。
三世諸佛。依般若波羅蜜多故。得阿耨多羅三藐三菩提。
故知般若波羅蜜多。是大神咒。是大明咒是無上咒。是無等等咒。能除一切苦。眞實不虚故。説般若波羅蜜多咒即説咒曰
掲帝掲帝　般羅掲帝　般羅僧掲帝 菩提僧莎訶
般若波羅蜜多心經
close #98
> テレビで過去のコメントが表示されるようにした

- app/controllers/pages_controller.rb
- app/javascript/comment.vue
- app/javascript/meal.vue
- app/models/nutrition.rb
- app/views/layouts/application.html.erb
- app/views/meals/show.html.erb
- app/views/pages/index.html.erb
- app/views/pages/tv.json.jbuilder
- db/migrate/20171205211715_change_nutrition.rb
- db/schema.rb
- spec/factories/nutritions.rb
- spec/models/nutrition_spec.rb
close #120 
close #121 
close #123
> テレビのレイアウトを整えた

- Gemfile
- Gemfile.lock
- app/controllers/nutritions_controller.rb
- app/views/nutritions/index.html.erb
とりあえず料理名検索だけするようにした。
close #122
> 栄養素の検索機能を追加

- config/environments/heroku.rb
> メールに残ってた忌まわしきstormy-oceanを消した
